### ISSUE TITLE
Tutorial explaining flite build process for new languages

### ISSUE THREAD

**Issue by saikrishnarallabandi** [festvox/flite#1]
This is a ToDo and I am hoping to get to this the last weekend in October. The idea is to build a tutorial describing the procedure to build a deployable voice in one Indian language that can expose the API capabilities of flite.

**Comment by saikrishnarallabandi** [comment]
Closing this for now. Will get back to this may be in summer 2018.

**Comment by sheikh-iffi** [comment]
Any progress on this issue?

**Comment by saikrishnarallabandi** [comment]
Hi.

Sorry this will take a while unfortunately since i have homeworks :p

Feel free to add a tutorial if you can
