### ISSUE TITLE
Compilation of cmu_indic_lex.c fails on MacOSX (ARM 64bit processor) due to missing function declaration.

### ISSUE THREAD

**Issue by roebel** [festvox/flite#104]
Hello

here a problem for compiling on MacOSX M2:

making in lang/cmu_indic_lex ...
gcc    -I../../include -g -O2 -Wall -no-cpp-precomp     -c cmu_indic_lex.c -o ../../build/arm-darwin23.1.0/obj/lang/cmu_indic_lex/cmu_indic_lex.o
cmu_indic_lex.c:305:13: error: call to undeclared function 'indic_digit_to_offset'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    flag = (indic_digit_to_offset(ccc) == -1)? !(indic_digit_to_offset(ddd) == -1):
            ^
1 error generated.
make[2]: *** [../../build/arm-darwin23.1.0/obj/lang/cmu_indic_lex/cmu_indic_lex.o] Error 1
make[1]: *** [../build/arm-darwin23.1.0/obj/lang/.make_build_dirs] Error 2
make: *** [build/arm-darwin23.1.0/obj//.make_build_dirs] Error 2

**Comment by nieder** [comment]
flite-2.2 on macOS x86_64 did not fail for me. Is this flite-2.1 or flite-2.2? I seem to recall a similar failure w/ flite-2.1.

**Comment by roebel** [comment]
Yep, that was 2.1. I am staying on that version because  I don't want to invest time into changing the rest of the project. I just wanted to share the fix. I understand this is fixed in the current version, so then I will close this issue.  
Best
