### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by attitudechunfeng** [festvox/flite#27]
there's  a memory leak problem in the function "ffeature_string", can you solve it?

**Comment by janblumenkamp** [comment]
Do you mind elaborating? Did you fix it or was it no memory leak after all? If you fixed it, how did you fix it?

**Comment by attitudechunfeng** [comment]
In fact, the problem occurred in the repository "http://downloads.sourceforge.net/hts-engine/flite%2Bhts_engine-1.07.tar.gz". I've found the leak problem in the line 179 of the file lib/flite_hts_engine.c, "ffeature_string(item, "R:SylStructure.parent.R:Syllable.syl_vowel")"，my solution is using a pointer point to the sentence, and then using cst_free function to free the memory.
