### ISSUE TITLE
some questions about stress

### ISSUE THREAD

**Issue by bringtree** [festvox/flite#45]
```bash
./t2p covina
pau k ow v iy1 n ax pau
```
 ``` 
cmudict-0.4.out
covina nil k ow0 v iy1 n ax0
```
Hello,  I meet some questions about the accent. 
In the training data, there are ow0, ax0.  there is not ow.
But when I use ./t2p to predict the words. I found the t2p print ow (not ow0)!
Could you help me?  I want to know the detail about how the flite deals with the accent? 
Thanks.

**Comment by lenzo-duo** [comment]
ow0 is equivalent to ow. The 1 is the marker for stress.
